// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WN7SJVh4gwmaCyRgPQvbtlYFjWW8Aoc',
    appId: '1:646433117706:android:33805fe2c64f6c8059b1f3',
    messagingSenderId: '646433117706',
    projectId: 'matjeralalmia',
    storageBucket: 'matjeralalmia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWNw9q--htImfL5Ez1RsgRGS2-LNNO5M',
    appId: '1:646433117706:ios:29906cad023b35eb59b1f3',
    messagingSenderId: '646433117706',
    projectId: 'matjeralalmia',
    storageBucket: 'matjeralalmia.appspot.com',
    androidClientId: '646433117706-a6usq6i46ct76v6m53ju6imumh2r8p4a.apps.googleusercontent.com',
    iosClientId: '646433117706-l66pvppkgstirt3atflmg0c2hrm6306n.apps.googleusercontent.com',
    iosBundleId: 'com.alalamia.alalamiaSpices',
  );
}
